# Referência Docker Compose: 
# https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md
version: '3.8'

services:
  app:
    # Imagem da aplicação do projeto hospedada no Gitlab Registry do IFCE
    # Envio de novas tags:
    # docker tag exemplo:latest gitlab.ifce.edu.br:5050/projetos/exemplo:1.0.1
    # docker push gitlab.ifce.edu.br:5050/projetos/exemplo:1.0.1
    image: gitlab.ifce.edu.br:5050/projetos/exemplo:1.0.1
    labels:
      app: "exemplo_app"
      equipe: "exemplo"
    # Caso sua aplicação não faça uso de variáveis de ambiente, remova esta seção
    environment:
      # Servidor PostgreSQL 16 de Produção
      POSTGRES_SERVER: 10.17.33.139
      # Se solicitado a criação de banco a equipe informará usuário e password file
      POSTGRES_USER: exemplo
      # Quando o container for criado no cluster existirá um volume tmpfs montado no caminho informado pela equipe,
      # cujo conteúdo será a senha do usuário no banco de dados. Dessa forma, não é necessário que a mesma esteja em 
      # texto claro no repositório.
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_exemplo_pass
      # Caso sua aplicação não consiga ler o valor de um Docker Secret, é possível usar a senha diretamente. Exemplo:
      # POSTGRES_PASSWORD: minhasenhasecreta1234
      TZ: America/Fortaleza
    entrypoint: ["docker-entrypoint-deploy.sh"]
    command: []
    deploy:
      # replicated = container normal
      # replicated-job = container que apenas executa uma tarefa e encerra
      mode: replicated
      # a necessidade de mais de uma réplica será avaliada pela equipe da DGTI
      replicas: 1
      # modo padrão para aplicações em execução no cluster
      endpoint_mode: dnsrr
      # valores padrão para alocação das aplicações de projeto no cluster
      placement:
        constraints:
          - node.role == worker
          - node.labels.ambiente == vcenter
      # instrução para indicar que caso o container falhe, ou seja, saia com status não 0,
      # o orquestrador do cluster tentará reiniciar a aplicação após o delay (ex.: 10s)
      restart_policy:
        condition: on-failure
        delay: 10s
      # informe os valores necessário para correta execuçaõ da sua aplicação
      # a equipe da DGTI avaliará os valores para que se adequem à infraestrutura disponível
      resources:
        # valores máximos de CPU e RAM que sua aplicação consumirá
        limits:
          cpus: '1.0'
          memory: 512M
        # o mínimo necessário para que sua aplicação consiga executar corretamente
        reservations:
          cpus: '0.05'
          memory: 128M
    # para que sua aplicação consiga se recuperar de um eventual estado de erro é necessário que 
    # a mesma possua uma checagem regular da saúde da aplicação
    healthcheck:
      # comando a ser executado dentro do container para checar se o serviço está sendo executado corretamente
      test: curl -s http://127.0.0.1:8000/
      # intervalo de tempo entre cada verificação de saúde do container
      interval: 15s
      # tempo máximo que o test deve responder para ser considerado saudável
      timeout: 5s
      # número de tentativas a serem executadas pelo healthcheck antes do orquestrador marcar o serviço como unhealthy
      retries: 5
      # tempo estimado de inicializaçãodo container, o healthcheck só começará a ser executado após start_period
      start_period: 30s
    # configuração de volume para armazenamento 
    volumes:
      - type: volume
        source: uploads
        target: /app/uploads/
    # configuração de Docker Secret (https://docs.docker.com/engine/swarm/secrets/), para aplicações que usam banco de dados
    secrets:
      # A secret com o namespace da sua aplicação será criada pela DGTI e deve ser referenciada em cada container que fará uso da mesma
      - pg_exemplo_pass
    # rede Docker padrão para projetos hospedados no cluster
    networks:
      - rede_projetos
  
  # serviços auxiliares da sua aplicação, se necessário
  redis:
    # caso precise uma imagem externa do GitHub utilize o Gitlab Dependency Proxy
    image: gitlab.ifce.edu.br/projetos/dependency_proxy/containers/redis:8.0.3-alpine
    labels:
      app: "exemplo_redis"
      equipe: "exemplo"
    # o healthcheck é obrigatório em todos os serviços
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.ambiente == vcenter
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 32M
    networks:
      - rede_projetos

# declaração dos recursos que foram previamente referenciados nos serviços (volumes, secrets e network)
# solicite à DGTI os recursos que for precisar:
# volume para cada diretório que sua aplicação precisa armazenar arquivos permanentes (ex.: arquivos, media, uploads)

volumes:
  # nome do volume
  uploads:
    driver_opts:
      # arquivos sempre serão armazenados em servidor NFS
      type: "nfs"
      # servidor de NFS de homologação: nfs-server-1
      o: "addr=nfs-server-1,rw,nfsvers=4"
      # caminho padrão que será criado no servidor de NFS
      device: ":/srv/nfs/exemplo/uploads"
 
secrets:
  # nome do Docker Secret criado pela DGTI contendo a senha do banco PostgreSQL 16
  pg_exemplo_pass:
    external: true
  # nome do Docker Secret criado pela DGTI contendo a senha do banco MariaDB
  mdb_exemplo_pass:
    external: true

networks:
  rede_projetos:
    driver: overlay
    external: true