# Referência Docker Compose: 
# https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md
version: '3.8'

services:
  app:
    image: 
    labels:
      app: "Sis-Invetario_app"
      equipe: "Sistema de Inventario"
    # Caso sua aplicação não faça uso de variáveis de ambiente, remova esta seção
    environment:
      TZ: America/Fortaleza
    env_file:
      - .env-prd
    entrypoint: ["docker-entrypoint-deploy.sh"]
    command: []
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
          - node.labels.ambiente == vcenter
      # instrução para indicar que caso o container falhe, ou seja, saia com status não 0,
      # o orquestrador do cluster tentará reiniciar a aplicação após o delay (ex.: 10s)
      restart_policy:
        condition: on-failure
        delay: 10s
      # informe os valores necessário para correta execuçaõ da sua aplicação
      # a equipe da DGTI avaliará os valores para que se adequem à infraestrutura disponível
      resources:
        # valores máximos de CPU e RAM que sua aplicação consumirá
        limits:
          cpus: '1.0'
          memory: 512M
        # o mínimo necessário para que sua aplicação consiga executar corretamente
        reservations:
          cpus: '0.05'
          memory: 128M
    # para que sua aplicação consiga se recuperar de um eventual estado de erro é necessário que 
    # a mesma possua uma checagem regular da saúde da aplicação
    healthcheck:
      # comando a ser executado dentro do container para checar se o serviço está sendo executado corretamente
      test: curl -s http://127.0.0.1:3000/
      # intervalo de tempo entre cada verificação de saúde do container
      interval: 15s
      # tempo máximo que o test deve responder para ser considerado saudável
      timeout: 5s
      # número de tentativas a serem executadas pelo healthcheck antes do orquestrador marcar o serviço como unhealthy
      retries: 5
      # tempo estimado de inicializaçãodo container, o healthcheck só começará a ser executado após start_period
      start_period: 30s
    # configuração de Docker Secret (https://docs.docker.com/engine/swarm/secrets/), para aplicações que usam banco de dados
    secrets:
      # A secret com o namespace da sua aplicação será criada pela DGTI e deve ser referenciada em cada container que fará uso da mesma
      - pg_ 
    # rede Docker padrão para projetos hospedados no cluster
    networks:
      - rede_projetos
 
secrets:
  # nome do Docker Secret criado pela DGTI contendo a senha do banco PostgreSQL 16
  pg_exemplo_pass:
    external: true
  # nome do Docker Secret criado pela DGTI contendo a senha do banco MariaDB
  mdb_exemplo_pass:
    external: true

networks:
  rede_projetos:
    driver: overlay
    external: true